[smtp]
# Fill these with your SMTP provider settings (Gmail example below)
host = "smtp.gmail.com"
port = 587
user = "your_gmail_address@gmail.com"
pass = "your_gmail_app_password"
from = "your_gmail_address@gmail.com"
# Default recipient (can be overridden by EMAIL_TO env var)
to = "petchpat@gmail.com" 